apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-main
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-main
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: server-main
    spec:
      nodeSelector:
        kubernetes.io/hostname: wk-02
      containers:
        - name: minecraft
          image: itzg/minecraft-server:java25
          resources:
            requests:
              memory: "8Gi"
          env:
            - name: EULA
              value: "TRUE"
            - name: RCON_ENABLED
              value: "true"
            - name: RCON_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mc-secrets
                  key: rcon-password
            - name: RCON_PORT
              value: "25575"
            - name: TYPE
              value: "PAPER"
            - name: VERSION
              value: "LATEST"
            - name: MEMORY
              value: "8G"
          ports:
            - containerPort: 25565
              name: minecraft
          volumeMounts:
            - name: server-data
              mountPath: /data
        - name: playit
          image: ghcr.io/playit-cloud/playit-agent:latest
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: playit-auth
                  key: key
        - name: filebrowser
          image: filebrowser/filebrowser:latest
          env:
            - name: FB_DATABASE
              value: "/srv/filebrowser.db"
            - name: FB_ROOT
              value: "/srv"
            - name: FB_LOG
              value: "stdout"
          ports:
            - containerPort: 80
              name: filebrowser
          volumeMounts:
            - name: server-data
              mountPath: /srv
      volumes:
        - name: server-data
          hostPath:
            path: /srv/minecraft
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: server-main-svc
  namespace: default
spec:
  type: NodePort
  selector:
    app: server-main
  ports:
    - port: 25565
      targetPort: 25565
      name: minecraft
      nodePort: 30065
    - port: 8080
      targetPort: 80
      name: filebrowser
      nodePort: 30080
